### ISSUE TITLE
TypeError Object.values is not a function

### ISSUE THREAD

**Issue by bcowgill** [bettiolo/babel-preset-es2017#37]
Perhaps this is just a configuration issue, but when I try to use this preset to transpile a call to Object.values so I can use it in the browser I get Object.values is not a function.

Looks like it's not installing a shim.

my original .babelrc was
{ "presets": ["react", "es2015", "stage-2"] } 

.babelrc: settings I tried:
{ "presets": ["react", "es2017"] } // causes me test failures in node
{ "presets": ["react", "es2017", "stage-3"] } // causes me test failures in node
{ "presets": ["react", "es2017", "stage-3", "es2015"] } // node tests pass, but in browser Object.values is not a function
{ "presets": ["react", "es2017", "stage-3", "es2015", "stage-2"] } // node tests pass, but browser error
{ "presets": ["react", "es2017", "stage-3", "es2016", "es2015"] } // node tests pass, but browser error
{ "presets": ["react", "es2015", "es2016", "es2017", "stage-3"] } // node tests pass, but browser error

I'm not sure if the order of presets matter so I tried a few things.

**Comment by bcowgill** [comment]
Well I solved it, found a shim.
Might be an idea to document which shims are needed on the docs page

npm install object.values

// Shim.js
import values from 'object.values');
if (!Object.values) {
    values.shim();
}

**Comment by bettiolo** [comment]
Thank you very much for your feedback!

This is the test covering the case and it works in node 5 which was the original target of the preset
https://github.com/bettiolo/babel-preset-es2017/blob/master/test/es2017.test.js#L19-L21

When I need to transpile my ES2017 code to ES5 I use this webpack configuration:

```js
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel',
        query: {
          presets: ['es2015', 'es2017', 'react'],
          plugins: ['transform-runtime', 'transform-decorators-legacy', 'transform-class-properties'],
        },
      },
    ],
```

**Comment by bettiolo** [comment]
The shims are added here: https://github.com/bettiolo/babel-preset-es2017/blob/v1.5.0/index.js#L27

I think that this may not work with webpack. I will review it the behaviour with it.

**Comment by bettiolo** [comment]
I can confirm that Webpack with ES2017 preset will not load the shims defined here: https://github.com/bettiolo/babel-preset-es2017/blob/v1.5.0/index.js#L27

**Comment by OZZlE** [comment]
why did you close this issue? what was the solution???
