### ISSUE TITLE
Transfer ownership to the babel repo?

### ISSUE THREAD

**Issue by hzoo** [bettiolo/babel-preset-es2017#42]
We should probably use a scoped name but I wanted to ask if you'd be cool with transferring ownership of the npm name to babel? (a similar request I made to babel-preset-es2016 in https://github.com/hzoo/babel-preset-es2016/issues/2). I also learned we don't really need the repo itself but more the npm name.

I'm https://www.npmjs.com/~hzoo on npm

**Comment by bettiolo** [comment]
Do you need the code as well?

**Comment by hzoo** [comment]
Nope just the npm name! (Don't need the code, or this repo)

**Comment by bettiolo** [comment]
How are you going to ensure that you are not going to break users?

**Comment by hzoo** [comment]
The next version that is published would have to be a major version

**Comment by bettiolo** [comment]
What kind of language coverage are you going to provide?

**Comment by hzoo** [comment]
The point of the preset will be to only provide transforms for what will be in es2017 (at this point async functions + trailing commas in functions) so users can choose what year to support. We can have other presets that combine them as well.

**Comment by bettiolo** [comment]
Hmm, you are not correct, look at the readme to see what will be included at this point in time in ES2017. Async functions are Stage 3, there is no certainty at all that it will be part of the spec.

So far, these are the finished proposals that will end up in the spec:
- Object.values/Object.entries | es7.object.values, es7.object.entries
- String.prototype.padStart/String.prototype.padEnd | es7.string.pad-start, es7.string.pad-end
- Object.getOwnPropertyDescriptors | get-own-property-descriptors
- Trailing Commas in Function Param Lists | syntax-trailing-function-commas

**Comment by hzoo** [comment]
The readme of this repo? async functions are stage 4 now. https://twitter.com/bterlson/status/758826160700530688

I just wanted to ask whether we could publish the preset `babel-preset-es2017` under the Babel org, otherwise we'll just need to use a different name. When we make the preset we would publish it as a major version bump so any existing users won't be affected. In the changelog I will make a note of this as well.

**Comment by bettiolo** [comment]
Sorry about that, I canceled my comment as I just updated the readme yesterday and it was not in stage 4 yet.

**Comment by bettiolo** [comment]
@hzoo how do you plan to handle: 
- Object.values/Object.entries, 
- String.prototype.padStart/String.prototype.padEnd, 
0 Object.getOwnPropertyDescriptors

They are part of the final stage, they are available in core-js but they are not in babel-polyfill as far as I am aware?

**Comment by hzoo** [comment]
The normal babel-presets (es2015, etc) don't provide those - we leave it up to the user to use a polyfill (babel-polyfill) or the transform-runtime package.

**Comment by bettiolo** [comment]
Can we provide the polyfills as part of the new package, like I did here: 
https://github.com/bettiolo/babel-preset-es2017/blob/master/polyfill.js

**Comment by loganfsmyth** [comment]
We generally treat babel plugins as aimed at making syntax work, with polyfilled library functionality being added via a polyfill. Seems like that is the responsibility of `core-js` to update, given that it was fairly recent, perhaps there has not been time? If not, we'd just want to add the content of https://github.com/bettiolo/babel-preset-es2017/blob/master/polyfill.js to `babel-polyfill` itself.

Would that be acceptable?

**Comment by bettiolo** [comment]
I think that that should be optional for people who wish to use ES2017 features. Hence why it should be (optionally) imported through the preset. We would keep everything needed for the full support of that language version in a single project.

**Comment by hzoo** [comment]
We can talk on #development on slack if you'd like

**Comment by hzoo** [comment]
You can also use https://www.npmjs.com/package/babel-preset-2017 instead? I also responded on https://github.com/babel/babel/pull/3642#issuecomment-240581701

**Comment by bettiolo** [comment]
Ownership transferred to @hzoo

**Comment by hzoo** [comment]
🙂  Thanks a lot @bettiolo! Will take your feedback/ideas into consideration
